apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-upgrade-crds
  namespace: {{ include "osm.namespace" . }}
  labels:
    {{- include "osm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-upgrade-crds
  namespace: {{ include "osm.namespace" . }}
  labels:
    {{- include "osm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-upgrade-crds
    namespace: {{ include "osm.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-upgrade-crds
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-upgrade-crds
  namespace: {{ include "osm.namespace" . }}
  labels:
    {{- include "osm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-upgrade-crds
  namespace: {{ include "osm.namespace" . }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
  labels:
    {{- include "osm.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: crds-upgrade
    spec:
      serviceAccountName: {{ .Release.Name }}-upgrade-crds
      restartPolicy: Never
      containers:
      - name: crds-upgrade
        image: "{{ .Values.OpenServiceMesh.image.registry }}/osm-crds:{{ .Values.OpenServiceMesh.image.tag }}"
        args:
            - apply
            - -f
            - /osm-crds
        imagePullPolicy: {{ .Values.OpenServiceMesh.image.pullPolicy }}
      nodeSelector:
        kubernetes.io/os: linux
{{- if .Values.OpenServiceMesh.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.OpenServiceMesh.imagePullSecrets | indent 8 }}
{{- end }}