{{- if .Values.OpenServiceMesh.featureFlags.enableMulticlusterMode }}
---
apiVersion: v1
kind: Service
metadata:
  name: osm-multicluster-gateway
  namespace: {{ include "osm.namespace" . }}
  labels:
    {{- include "osm.labels" . | nindent 4 }}
    app: osm-multicluster-gateway
spec:
  ports:
    - name: multicluster
      port: 15443
      targetPort: 15443
  selector:
    app: osm-multicluster-gateway
  type: LoadBalancer
{{- end }}